

quarkus.http.port=8080

quarkus.datasource.db-kind=mySql
quarkus.datasource.username=MYSQL_USER
quarkus.datasource.password=MYSQL_PASSWORD

quarkus.datasource.jdbc.url=jdbc:mysql://myquizserver.cjroxib0ljpb.eu-west-2.rds.amazonaws.com:3306/myquizappdb
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.generation=update